server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changce?useSSL=false
    username: root
    password: a
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.fourteam.changce.pojo
  mapper-locations: classpath:mapper/*.xml
